name: Build and Deliver

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22' # Update based on your Spring Boot requirements

      - name: Build Project with Maven
        run: mvn clean package -DskipTests
        env:
          MAVEN_OPTS: '-Xmx1024m'

      - name: Deliver Artifact to Runner
        run: |
          cp target/buttentica-0.0.1.jar /home/jeus/buttentica/buttentica.jar

      - name: Run Application with Secrets
        run: |
          java -jar /home/jeus/buttentica/buttentica.jar
        env:
          DB_PATH: ${{ secrets.DB_PATH }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}