name: Build and Deliver

on:
  push:
    branches:
      - master
env:
  BUILD_NUMBER: ${{ github.run_number }}
jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: Buttentica_stage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21' # Update based on your Spring Boot requirements

      - name: Build Project with Maven
        run: mvn clean package -DskipTests
        env:
          MAVEN_OPTS: '-Xmx1024m'

      - name: Deliver Artifact to Runner
        run: |
          cp target/buttentica-0.0.1.jar /home/jeus/buttentica/buttentica.jar

      - name: Run Application with Secrets
        run: |
          echo "VERSION=$BUILD_NUMBER" | sudo tee /etc/systemd/system/buttentica.env
          echo "DB_PATH=${{ secrets.DB_PATH }}" | sudo tee -a /etc/systemd/system/buttentica.env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" | sudo tee -a /etc/systemd/system/buttentica.env
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" | sudo tee -a /etc/systemd/system/buttentica.env
          java -version 
          sudo systemctl restart buttentica.service
#        env:
#          DB_PATH: ${{ secrets.DB_PATH }}
#          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}